#pragma once


namespace LogicLayer
{
	enum class LOGIC_ERROR_SET : short
	{
		NONE = 0,
		UNASSIGNED_ERROR = 201,
		MAIN_INIT_NETWORK_INIT_FAIL = 206,
		USER_ID_DUPLICATE = 207,


		MAX_CLIENT_MANAGER = 208,
		CLIENT_MGR_INDEX_ERR = 209,
		CLIENT_MGR_NOT_EXIST = 210,


		LOBBY_ENTER_MAX_USER_COUNT = 211,
		LOBBY_ENTER_USER_DUPLICATION = 212,
		LOBBY_LEAVE_USER_INVALID_INDEX = 213,
		LOBBY_ENTER_EMPTY_USER_LIST = 214,
		LOBBY_ADD_FAIL = 215



	};
}