#pragma once


namespace NetworkLayer
{
	enum class NET_ERROR_SET : short
	{
		NONE = 0,

		SERVER_SOCKET_CREATE_FAIL = 11,
		SERVER_SOCKET_SO_REUSEADDR_FAIL = 12,
		SERVER_SOCKET_BIND_FAIL = 14,
		SERVER_SOCKET_LISTEN_FAIL = 15,
		SERVER_SOCKET_FIONBIO_FAIL = 16,

		SEND_CLOSE_SOCKET = 21,
		SEND_SIZE_ZERO = 22,
		CLIENT_SEND_BUFFER_FULL = 23,
		CLIENT_SEND_BUFF_NOT_CONNECTION = 24,

		ACCEPT_ERROR = 26,
		ACCEPT_MAX_COUNT = 27,
		ACCEPT_API_WSAEWOULDBLOCK = 28,

		RECV_API_ERROR = 32,
		RECV_BUFFER_OVERFLOW = 32,
		RECV_REMOTE_CLIENT_CLOSE = 33,
		RECV_PROCESS_NOT_CONNECTED = 34,
		RECV_CLIENT_MAX_PACKET = 35,

		SEND_BUFF_REMOTE_CLOSE = 36
	};

	enum class SOCKET_CLOSE_CASE : short
	{
		SESSION_POOL_MAX = 1,
		SELECT_ERROR = 2,
		RECV_ERROR = 3,
		RECV_BUFFER_PROCESS_ERROR = 4,
		SEND_ERROR = 5,
		FORCING_CLOSE = 6,
		CLIENT_MGR_FULL = 7
	};
}